services:
  postgre-vector-db:
    image: 'pgvector/pgvector:pg17'
    ports:
      - '5431:5432'
    volumes:
      - 'postgre-vector-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

volumes:
  postgre-vector-data: